### PR TITLE
ObjectTracker Feature

### PR DESCRIPTION
**Pull request by sgmurray**
The SkyEye allows user code to get the positions/velocities of other objects/robots in the world. In the soccer game this is used to track the ball, teammates , and opponents.

### CODE REVIEW

**Comment by QuirkyCort** [comment]
Got a better name than SkyEye? From the name, it may not be obvious to the students what this does.

**Comment by sgmurray** [comment]
How about MotionTracker or Radar?

**Comment by QuirkyCort** [comment]
Radar seems to imply a relative bearing / distance data.

I'm thinking...

ObjectTracker or TargetTracker: Simple and straightforward.

or

AIS: Automatic Identification System: Seems fitting to me, but probably unfamiliar to anyone outside of the marine industry.

I'll let you decide.

**Comment by sgmurray** [comment]
I renamed it to ObjectTracker.

**Comment by QuirkyCort** [comment]
Not sure if Robot.js is the best place for this. I can envision games worlds that enforces different rules (eg. cannot get opponent position).

Well, it can always be changed later. Merging now.

**Comment by sgmurray** [comment]
I went back and forth about whether the ObjectTracker should be built into the robot or be a component. 

I think it  makes sense to make something a component if its physical location/rotation affects how it operates. For example, a downwards facing color sensor behaves very differently from a forwards facing one. On the other hand, things like the Radio, Speaker, and ObjectTracker behave exactly the same regardless of where the physical component is.

Another thought is to add a ObjectTrackerVisible property to robots. It would default to false, but special worlds i.e soccer would set it to true.

**Comment by QuirkyCort** [comment]
I agree that it shouldn't be a component. What I'm considering is whether the object tracking should be managed by each individual world_xxx.js.

Letting the world manage tracking will allow the world designer more flexibility in when and where tracking is available, for example...

- No detection of opponents (...use ultrasonic / laser for that)
- No detection of team mates (...use radio to communicate position)
- No reception zone (...robot get no data from ObjectTracker when in the zone)
- No detection zone (...robots in that zone are not detectable)
- "Cloak" power up that renders a robot undetectable to its opponent for some time

The first two can be a meaningful option to add to football, while the rest may be useful for other types of robot games.

**Pull request merged**
