### PR TITLE
Trinity Firefighting competition

### PR DESCRIPTION
**Pull request by Yuvix25**
Added the Trinity Firefighting competition arena.

### CODE REVIEW

**Comment by Yuvix25** [comment]
This is the code of the Trinity Firefighting competition that you have discussed about with my teacher, can you merge this pull request?

**Comment by QuirkyCort** [comment]
Sorry. Been busy with work and family. Haven't had time to review the PR. If it's urgent, let me know and I'll prioritize it.

**Comment by Yuvix25** [comment]
It is pretty urgent, so if you can please review it

**Comment by QuirkyCort** [comment]
Appreciate if you can share the reason for the urgency.

**Comment by Yuvix25** [comment]
Since we are restricted with covid19 lockdowns, we are using alternatives to the real-world robots and arenas.
For many of us teachers, the “GearsBot HFFR world” allow to train our students in address the "HFFR navigation challenge", to demonstrate their programing skills, strategy and problem solving. 
We need the simulator as a teaching tools, now more than ever before, in 2021 2nd semester, in this situation forced on us, that allow only or mainly E-Learning.

**Comment by QuirkyCort** [comment]
Alright. I'll try to prioritize it.

In the meantime, you can enable "Github pages" (...look under Settings -> Options -> Github pages). That will enable your repository copy to be directly served to your students via https://yuvix25.github.io/gears/public/

**Comment by Yuvix25** [comment]
Thank you for the advice, I have merged your updated version into my version with the Trinity Firefighting, and it is in GIthub Pages for now, but it will be the best if you will merge this PR so that I won't have to remerge every time you push a new version.

**Comment by QuirkyCort** [comment]
Hi Yuvix. Sorry for taking so long.

I've reviewed the code. It's an interesting map, but I can't accept it as it is. Reasons are...

1) There are some Google Analytics tracking code in there. I can't accept that.

2) It changes some of the defaults and units in image world. That will break other people's configurations.

If you're ok with it, I can manually add in the TFC map and robot alone, but exclude the rest.

**Comment by Yuvix25** [comment]
About the Google Analytics, ai can remove it, but I don't remember changing the units, can you be more specific?

**Comment by QuirkyCort** [comment]
Basically, the changes in world_image.js. Defaults were changed and rotation units changed from radians to degrees.

**Comment by Yuvix25** [comment]
Can you merge without world_image.js?
(It will not effect the TFC, which is the only thing I meant to add)

**Comment by QuirkyCort** [comment]
No. I cannot pick and choose files from a PR. You either have to fix it on your end, or I'll have to manually add the TFC map and robot in my own commit

**Comment by Yuvix25** [comment]
OK, I will soon fix world_image.js and push to my version.

**Comment by QuirkyCort** [comment]
I'm gonna have to close this. If you have some changes that you'll like to merge into the main branch, create another pull request.

**Pull request closed without merging**
