### PR TITLE
Code sep 2

### PR DESCRIPTION
**Pull request by humbug99**
This is a new implementation for issue #5.  This code branch supports multiple python modules, each in a different tab.  Modules can import from other modules.  The UI is somewhat inspired by the trinket UI.  To create a module, click the + icons on the Python tab. Each of the Python and module tabs has upload and download icons, and the module tabs have a - icon that allows you to delete the module.  To change a module name, just click on the name.

Sample code is in samples/python/multi_module: To try it, activate the python tab and upload the hello_with_2module.py file.  Then click the + button twice to create two modules/tabs, in these tabs use the upload buttons to upload the code for library.py and lib2.py, then run the simulation.

Exporting to zip includes py files for the modules, but I didn't add the zip import yet.

No support yet for creating blockly blocks from module defs either.

This PR supersedes the other PR for issue 5, which only supported a single library module. I suggest closing the other PR.

### CODE REVIEW

**Comment by QuirkyCort** [comment]
Thanks. I'm going through it and will make a few changes before merging. I'll provide comments here as I go along...

**Comment by QuirkyCort** [comment]
```
// second arg: 0 replace all, -1 start, 1 end
// this used to be 1, I think 0 is more appropriate
pythonPanel.editor.setValue(this.result, 0);
```

The second value is for the cursor position. https://ace.c9.io/api/editor.html#Editor.setValue

I find setting it to 1 (place cursor at end) is a less annoying than setting it to 0 (select all).

**Comment by QuirkyCort** [comment]
All the css files are generated by SASS https://sass-lang.com/ so I'll mirror the changes to the scss files. SASS makes dealing with CSS a lot less painful...

Technically, I don't need to include the css files in the repository (...since they are all generated by SASS), but it's easier for others to host Gears on their own if the full set of html / js / css are included.

**Comment by QuirkyCort** [comment]
I'll rather keep the list of python files in a separate, scrollable, tab list on the bottom (...kind of like Google sheets), but I think it's ok for now.

**Comment by QuirkyCort** [comment]
Couple of bugs...

1) First add, edit, then delete a module (module1.py). We should have no modules now. If I add a module again (...it'll reuse the name "module1.py"), it'll be populated with the previous content.

2) If a module is deleted then re-added, the new module will be uneditable.

This one will have to be fixed before I can merge the PR.

**Comment by humbug99** [comment]
Thanks for all of the useful feedback.
I'll look at the bugs ASAP.

**Comment by QuirkyCort** [comment]
Trailing commas are allowed and fairly common in JS. I don't enforce it, but there's also no need to strip them out.

**Comment by QuirkyCort** [comment]
Rather than having a pythonLibPanel.js, I believe it would be more efficient to use pythonPanel and simply change the content in the editor. Not a big deal. Ok for now.

**Comment by humbug99** [comment]
I committed a fix for the two bugs you found.  I presume that for #1 you wanted the new module ("module1") to start with no text.  That seemed reasonable since I would expect that most of the time the use case is to either create a new module, or add a module, then upload code to it.

I was going to try and merge the changes into the scss files too, but the version of sass that I tried generated different whitespace, which made it look like a much bigger change set.  For my future reference, what version of sass are you using?

**Comment by QuirkyCort** [comment]
I'm using "Sass 3.4.23 (Selective Steve)". It's the older Ruby version. Don't worry about the whitespaces. The css files are dynamically generated, so I don't bother with changes there. As mentioned, they are only there for convenience.

I'll merge it after testing.

**Comment by humbug99** [comment]
Gentle bump on this pr.  As far as I know I fixed the two bugs that you found, if you want further revisions to the pr, please specify what is needed.

**Comment by QuirkyCort** [comment]
Frankly, I've been too busy to test this. Doesn't look like it breaks anything, so I'll just merge it now and look through it another time.

Let me know how I should credit you for this. There's a good amount of code contributed, and I really appreciate it.

**Pull request merged**
